import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Terms of Service — QueryAI',
  description: 'Terms and conditions for using the QueryAI platform.',
}

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />

      <main className="flex-1 mx-auto max-w-3xl w-full px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-4xl font-extrabold tracking-tight text-foreground">Terms of Service</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: May 20, 2025</p>
        </div>

        <div className="prose prose-sm max-w-none space-y-8 text-muted-foreground">
          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>
              By using QueryAI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not
              agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">2. Description of Service</h2>
            <p>
              QueryAI provides a natural language interface for generating SQL queries from uploaded data files.
              The Service uses third-party AI models to interpret questions and produce SQL. Results are provided
              for informational purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">3. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc ml-5 mt-2 space-y-1">
              <li>Upload files containing illegal, harmful, or offensive content</li>
              <li>Attempt to bypass security guardrails or execute destructive queries</li>
              <li>Use the Service to process personally identifiable information without consent</li>
              <li>Reverse-engineer, scrape, or abuse the Service API</li>
              <li>Use the Service for any illegal purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">4. Data Responsibility</h2>
            <p>
              You are solely responsible for the data you upload. Do not upload sensitive personal data,
              financial records, health information, or any data you are not authorized to process. QueryAI
              is not responsible for data uploaded by users.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">5. AI-Generated Content</h2>
            <p>
              SQL queries and explanations are generated by AI models and may contain errors. Always review
              generated SQL before executing it in a production database. QueryAI is not liable for damages
              caused by incorrect or incomplete AI-generated output.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">6. Intellectual Property</h2>
            <p>
              The QueryAI platform, including its source code, design, and documentation, is proprietary.
              User-uploaded data remains the property of the uploader. Generated SQL queries based on your
              data are yours to use freely.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">7. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. QueryAI shall not be liable
              for any indirect, incidental, or consequential damages arising from your use of the Service,
              including data loss, inaccurate query results, or service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate access to the Service at any time, with or without
              notice, for violations of these terms or any other reason.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">9. Changes to Terms</h2>
            <p>
              We may modify these terms at any time. Updated terms will be posted on this page. Continued use
              of the Service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">10. Contact</h2>
            <p>
              For questions about these terms, contact us at{' '}
              <a href="mailto:legal@queryai.dev" className="text-primary hover:underline">
                legal@queryai.dev
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
